version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'crowdeval'
      MYSQL_DATABASE: 'crowdeval'
      MYSQL_USER: 'crowdeval'
      MYSQL_PASSWORD: 'crowdeval'
    volumes:
      - 'cedb:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  mysql-test:
    image: 'mysql:8.0'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'crowdeval'
      MYSQL_DATABASE: 'crowdeval-test'
      MYSQL_USER: 'crowdeval'
      MYSQL_PASSWORD: 'crowdeval'
    volumes:
      - 'cedb_test:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.11.1'
    ports:
      - '9200:9200'
    environment:
      discovery.type: 'single-node'
    volumes:
    - 'cesearch:/usr/share/elasticsearch/data'
  bert:
    build:
      context: './infrastructure/bert'
      dockerfile: Dockerfile
    ports:
    - '5555:5555'
    - '5556:5556'
volumes:
  cedb:
  cedb_test:
  cesearch: