version: '2.0'
services:
  mysql:
    image: 'mysql:8.0'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'crowdeval'
      MYSQL_DATABASE: 'crowdeval'
      MYSQL_USER: 'crowdeval'
      MYSQL_PASSWORD: 'crowdeval'
    volumes:
      - 'cedb:/var/lib/mysql'
    networks:
      - crowdeval
# if you want to run the web app outside docker
# uncomment this to expose the ports outside
# the docker network
#    ports:
#      - '${DB_PORT}:3306'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.11.1'
    restart: always
    environment:
      discovery.type: 'single-node'
    volumes:
    - 'cesearch:/usr/share/elasticsearch/data'
    networks:
      - crowdeval
# if you want to run the web app outside docker
# uncomment this to expose the ports outside
# the docker network
#    ports:
#      - '9200:9200'

  bert:
    build:
      context: './bert'
      dockerfile: Dockerfile
    restart: always
    networks:
      - crowdeval
# if you want to run the web app outside docker
# uncomment this to expose the ports outside
# the docker network
#    ports:
#      - '5555:5555'
#      - '5556:5556'

  redis:
    image: 'redis:6.2'
    restart: always
    networks:
      - crowdeval
# if you want to run the web app outside docker
# uncomment this to expose the ports outside
# the docker network
#    ports:
#      - '6379:6379'


  crowdeval:
    build:
      context: './webapp'
      dockerfile: 'infrastructure/docker/Dockerfile'
    restart: always
    ports:
      - '8000:8000'
    networks:
      - crowdeval
    depends_on:
      - 'mysql'
      - 'elasticsearch'
      - 'bert'
      - 'redis'

volumes:
  cedb:
  cesearch:

networks:
  crowdeval:
    driver: bridge
