version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'cedb:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  mysql-test:
    image: 'mysql:8.0'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}-test'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'cedb_test:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
volumes:
  cedb:
  cedb_test: