version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'crowdeval'
      MYSQL_DATABASE: 'crowdeval'
      MYSQL_USER: 'crowdeval'
      MYSQL_PASSWORD: 'crowdeval'
    volumes:
      - 'cedb:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  mysql-test:
    image: 'mysql:8.0'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'crowdeval'
      MYSQL_DATABASE: 'crowdeval-test'
      MYSQL_USER: 'crowdeval'
      MYSQL_PASSWORD: 'crowdeval'
    volumes:
      - 'cedb_test:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
volumes:
  cedb:
  cedb_test: