"""Add posts table

Revision ID: d38c9ab2e1d1
Revises: f247b74f218f
Create Date: 2021-03-01 17:58:39.539273

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd38c9ab2e1d1'
down_revision = 'f247b74f218f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('external_post_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_username', sa.String(length=255), nullable=False),
    sa.Column('author_profile_url', sa.String(length=255), nullable=False),
    sa.Column('external_author_id', sa.String(length=64), nullable=False),
    sa.Column('additional_metadata', mysql.JSON(), nullable=True),
    sa.Column('external_created_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
