"""empty message

Revision ID: e548cfba9560
Revises: bd2fc69a03b9
Create Date: 2021-03-09 17:00:49.657755

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e548cfba9560'
down_revision = 'bd2fc69a03b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rating',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_rating')
    # ### end Alembic commands ###
