name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Poetry
        run: pip install poetry==1.1.4
      - name: Node Cache
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "15.x"
          registry-url: "https://registry.npmjs.org"
      - name: Poetry Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Python dependencies
        run: poetry install
      - name: Install Node dependencies
        run: npm ci
      - run: cp .env.example .env
      - name: Run Node lints
        run: npm run lint-js
      - name: Run Python lints
        run: npm run lint-py -- --check
      # - name: Run Python tests
      #   run: flask test