name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp .env.ci .env
      - name: Start CI Environment
        run: docker-compose up -d mysql-test # only boot services required
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Poetry
        run: pip install poetry==1.1.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "15.x"
          registry-url: "https://registry.npmjs.org"
      - name: Poetry Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Node Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Python dependencies
        run: poetry install
      - name: Install Node dependencies
        run: npm ci
      - name: Node Lints
        run: npm run lint
      - name: Python Lints
        run: poetry run flask lint --check
      - name: Python Tests
        run: poetry run flask test